xtest: stats: remove <sys/stat.h>
The <sys/stat.h> header is not used by host/xtest/stats.c and causes a
conflict when musl is used. Therefore remove it.

 | In file included from optee-test/4.1.0/recipe-sysroot/usr/include/sys/stat.h:23,
 | from optee-test/4.1.0/git/host/xtest/stats.c:17:
 | optee-test/4.1.0/recipe-sysroot/usr/include/bits/stat.h:17:26: error: expected identifier or '(' before '[' token
 | 17 | unsigned __unused[2];
 | | ^

Reported-by: Jon Mason <jon.mason@arm.com>
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Joakim Bech <joakim.bech@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>