xtest: pkcs11: fix compile error with init_{user_,}test_token()
Commit b38e9e06fcbd ("xtest: pkcs11: add PKCS11 ACL auth test") split
init_{user_,}test_token() into init_{user_,}test_token_pin_auth() and
init_{user_,}token_acl_auth() but omitted to update a couple of call
sites. Fix them.

Fixes the following compile errors:

 pkcs11_1000.c: In function ‘xtest_pkcs11_test_1026’:
 pkcs11_1000.c:8537:7: error: implicit declaration of function ‘init_test_token’ [-Werror=implicit-function-declaration]
  8537 |  rv = init_test_token(slot);
       |       ^~~~~~~~~~~~~~~
 pkcs11_1000.c:8537:7: error: nested extern declaration of ‘init_test_token’ [-Werror=nested-externs]
 pkcs11_1000.c:8541:7: error: implicit declaration of function ‘init_user_test_token’; did you mean ‘init_user_test_token_acl_auth’? [-Werror=implicit-function-declaration]
  8541 |  rv = init_user_test_token(slot);
       |       ^~~~~~~~~~~~~~~~~~~~
       |       init_user_test_token_acl_auth
 pkcs11_1000.c:8541:7: error: nested extern declaration of ‘init_user_test_token’ [-Werror=nested-externs]

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>