xtest: regression: Fix compilation error
Following error is thrown in Yocto build:

  | .../optee-test/.../git/host/xtest/regression_1000.c: In function 'xtest_tee_test_1033':
  | .../optee-test/.../git/host/xtest/regression_1000.c:2421:4: error: ignoring return value of 'fread', declared with attribute warn_unused_result [-Werror=unused-result]
  |  2421 |    fread(from_file, sizeof(char), sizeof(to_plugin), fp);
  |       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 01f6f06 ("regression: add tests for the supplicant plugin framework")
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Reviewed-by: Jerome Forissier <jerome@forissier.org>
Signed-off-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>