host: xtest_10000: remove unused static array
Newer (Linaro) compilers complain

```
.../optee_test/host/xtest/xtest_10000.c:300:22: error: 'pbkdf2_4_dkm' defined but not used [-Werror=unused-const-variable=]
```

and break the build.

Signed-off-by: Andy Green <andy@warmcat.com>