regression 4100: fix uninitialized local variable
Reported by GCC 8.2.0 with traces like:

.../build/optee_test/host/xtest/regression_4100.c:884:2: error: ‘cres’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  ADBG_EXPECT_COMPARE_SIGNED(c, cres, ==, cmp_res);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../build/optee_test/host/xtest/regression_4100.c:869:10: note: ‘cres’ was declared here
  int32_t cres;
          ^~~~
.../build/optee_test/host/xtest/regression_4100.c:857:2: error: ‘cres’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  ADBG_EXPECT_COMPARE_SIGNED(c, cres, ==, cmp_res);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../build/optee_test/host/xtest/regression_4100.c:835:10: note: ‘cres’ was declared here
  int32_t cres;
          ^~~~

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>