Android.mk: add -Wno-unused-parameter CFLAGS for xtest
Commit bcd55831e1f7 ("xtest: add asymmetric cipher perf test")
introduces a build error for xtest on AOSP 14:

external/optee_test/host/xtest/asym_perf.c:125:71: error: unused parameter 'main_algo' [-Werror,-Wunused-parameter]
static void usage(const char *progname, uint32_t width_bits, uint32_t main_algo,
                                                                      ^
external/optee_test/host/xtest/asym_perf.c:126:14: error: unused parameter 'mode' [-Werror,-Wunused-parameter]
                  uint32_t mode, uint32_t salt_len, uint32_t size,
                           ^
external/optee_test/host/xtest/asym_perf.c:127:14: error: unused parameter 'crypto_algo' [-Werror,-Wunused-parameter]
                  uint32_t crypto_algo, int warmup, uint32_t l, uint32_t n)
                           ^
external/optee_test/host/xtest/asym_perf.c:668:76: error: unused parameter 'size' [-Werror,-Wunused-parameter]
static int check_rsa_hash_params(uint32_t crypto_algo, int width_bits, int size,
                                                                           ^
4 errors generated.
13:15:41 ninja failed with: exit status 1

Adding -Wno-unused-parameter to the build flags seems a reasonable fix
since this is a test executable.

Add it to fix the build error.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>