xtest: fix build with GP_PACKAGE and GCC 14
Fix the following build error (QEMU build in this instance):

$ export GP=TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z
$ make -j$(nproc) GDBSERVER=y \
    GP_PACKAGE=/home/builder/optee/$GP
[...]
/home/builder/optee/out-br/build/optee_test_ext-1.0/host/xtest/gp_10000.c: In function 'gp_test_teec_10086':
/home/builder/optee/out-br/build/optee_test_ext-1.0/host/xtest/gp/include/xml_client_api.h:162:18: error: allocation of insufficient size '0' for type 'uint8_t' {aka 'unsigned char'} with size '1' [-Werror=alloc-size]
  162 |         temp_mem = malloc(size)
      |                  ^
/home/builder/optee/out-br/build/optee_test_ext-1.0/host/xtest/gp_10000.c:1757:5: note: in expansion of macro 'AllocateTempMemory'
 1757 |     AllocateTempMemory(TEMP_MEM01, ZERO);
      |     ^~~~~~~~~~~~~~~~~~

The root cause is, when GDBSERVER=y the cross compiler is built by
Buildroot and is GCC 14, while the default one is GCC 11.3. GCC 14
reports the additional wrning/error which therefore needs to be
disabled explicitly (we don't want to change the GP test).

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>