xtest: fix compilation error with WITH_OPENSSL=n
Fix the following compilation error:
$ CROSS_COMPILE=... OPTEE_CLIENT_EXPORT=... TA_DEV_KIT_DIR=... \
  WITH_OPENSSL=n make

/optee_test/host/xtest/xtest_uuid_helpers.c: In function ‘xtest_uuid_to_allocated_str’:
/optee_test/host/xtest/xtest_uuid_helpers.c:91:13: error: implicit declaration of function ‘malloc’ [-Werror=implicit-function-declaration]
   91 |         s = malloc(UUID_STR_LEN);
      |             ^~~~~~
/optee_test/host/xtest/xtest_uuid_helpers.c:16:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
   15 | #include "xtest_uuid_helpers.h"
  +++ |+#include <stdlib.h>
   16 |
/optee_test/host/xtest/xtest_uuid_helpers.c:91:13: error: incompatible implicit declaration of built-in function ‘malloc’ [-Werror=builtin-declaration-mismatch]
   91 |         s = malloc(UUID_STR_LEN);
      |             ^~~~~~
/optee_test/host/xtest/xtest_uuid_helpers.c:91:13: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
/optee_test/host/xtest/xtest_uuid_helpers.c:95:9: error: implicit declaration of function ‘sprintf’ [-Werror=implicit-function-declaration]
   95 |         sprintf(s, "%08x-%04x-%04x-%02x%02x-%02x%02x%02x%02x%02x%02x", uuid->timeLow,
      |         ^~~~~~~
/optee_test/host/xtest/xtest_uuid_helpers.c:16:1: note: include ‘<stdio.h>’ or provide a declaration of ‘sprintf’
   15 | #include "xtest_uuid_helpers.h"
  +++ |+#include <stdio.h>
   16 |
/optee_test/host/xtest/xtest_uuid_helpers.c:95:9: error: incompatible implicit declaration of built-in function ‘sprintf’ [-Werror=builtin-declaration-mismatch]
   95 |         sprintf(s, "%08x-%04x-%04x-%02x%02x-%02x%02x%02x%02x%02x%02x", uuid->timeLow,
      |         ^~~~~~~
/optee_test/host/xtest/xtest_uuid_helpers.c:95:9: note: include ‘<stdio.h>’ or provide a declaration of ‘sprintf’
cc1: all warnings being treated as errors

Fixes: b38e9e06fcbd ("xtest: pkcs11: add PKCS11 ACL auth test")
Signed-off-by: Clement Faure <clement.faure@nxp.com>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>