regression 4000: fix uninitialized local variable
Reported by GCC 8.2.0 with trace:

.../build/optee_test/host/xtest/regression_4000.c:4090:24: error: ‘ptx_hash_size’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     if (!ADBG_EXPECT_TEEC_SUCCESS(c,
                        ^~~~~~~~~~~~~
.../build/optee_test/host/xtest/regression_4000.c:3658:9: note: ‘ptx_hash_size’ was declared here
  size_t ptx_hash_size;
         ^~~~~~~~~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>