Android.mk: add subkeys include directory
Since commit dd336daac37e ("regression: add test case 1039 for
subkey"), a testcase for subkey was added to xtest. Add their
include dir to the android build and fix the following errors:

FAILED: out/target/product/i350_manefaces/obj/EXECUTABLES/xtest_intermediates/host/xtest/xtest_test.o external/optee_test/host/xtest/xtest_test.c:26:10: fatal error: 'ta_subkey1.h' file not found
FAILED: out/target/product/i350_manefaces/obj/EXECUTABLES/xtest_intermediates/host/xtest/xtest_test.o external/optee_test/host/xtest/xtest_test.c:27:10: fatal error: 'ta_subkey2.h' file not found

Signed-off-by: Vitor Sato Eschholz <vsatoes@baylibre.com>
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>