xtest: regression 1027: fix build warning when openssl not used
Fix build warning reported with trace message like below:

.../optee-test-custom/host/xtest/regression_1000.c:2049:20: error: ‘client_uuid_linux_ns’ defined but not used [-Werror=unused-variable]
 static const char *client_uuid_linux_ns = "58ac9ca0-2086-4683-a1b8-ec4bc08e01b6";
                    ^~~~~~~~~~~~~~~~~~~~

Fixes: 8e070bc41e1d ("xtest: disable tests 1027 and 1028 if no OpenSSL")
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>