host: supp_plugin: add missing dependency on teec
Adds missing dependency of supp_plugin test on libteec header files
that are brought in by libteec. The issue was reported by compiler with
the below build error message:

/tmp/optee/optee_test/host/supp_plugin/test_supp_plugin.c:12:10: fatal error: tee_plugin_method.h: No such file or directory
   12 | #include <tee_plugin_method.h>
      |          ^~~~~~~~~~~~~~~~~~~~~

Acked-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>