ta: storage: maybe usued TA UUID in clear_storage()
Adds __maybe_unused attribute to local variable hold the TA UUID
to fix build warning reported by GCC with the below trace:

../storage/storage.c: In function ‘clear_storage’:
../storage/storage.c:674:18: error: unused variable ‘uuid’ [-Werror=unused-variable]
  674 |         TEE_UUID uuid = TA_UUID;
      |                  ^~~~

Fixes: aa43c9084e21 ("xtest: add --clear-storage option")
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Signed-off-by: Etienne Carriere <etienne.carriere@foss.st.com>